export const institutions: string[] = [
	'South African Universities Outlook',
	'The University of Cape Town',
	'Stellenbosch University',
	'University of Pretoria',
	'University of the Witwatersrand',
	'University of Kwazulu Natal',
	'University of the Western Cape',
	'Rhodes University',
	'The University of South Africa',
	'University of Johannesburg',
	'North West University',
	'University of the Free State',
	'Nelson Mandela Metropolitan University',
	'Cape Peninsula University of Technology',
	'Durban University of Technology',
	'University of Zululand',
	'Monash University',
	'Vaal University of Technology',
	'Central University of Technology',
	'Walter Sisulu University',
	'University of Limpopo',
	'Tshwane University of Technology',
	'University of Fort Hare',
	'Academy for Facilities Management (A4FM)',
	'ACT Cape Town',
	'Belgium Campus',
	'BMT College',
	'Boland College',
	'Boston City Campus & Business College',
	'Buffalo City Public College',
	'Central Johannesburg College',
	'Centurion Academy',
	'Coastal KZN College',
	'College of Cape Town',
	'College of Production Technology (CPT)',
	'College of the Transfiguration',
	'College SA',
	'Concept Interactive',
	'CTI Education Group',
	'Damelin',
	'Durbanville College',
	'Eastcape Midlands College',
	'Ehlanzeni College',
	'Ekhurhuleni West College',
	'Ekurhuleni East College',
	'Elangeni College',
	'Esayidi College',
	'Eta College',
	'False Bay College',
	'FEDISA',
	'Flavius Mareka College',
	'George Whitefield College',
	'Gert Sibande College',
	'Helderberg College',
	'ICESA City Campus',
	'Intec College',
	'International Peace College South Africa',
	'King Hintsa College',
	'King Sabata Dalindyebo College',
	'Lephalale College',
	'Letaba College',
	'Lovedale College',
	'Lyceum Correspondence College',
	'Majuba College',
	'Maluti College',
	'Midrand Graduate Institute (MGI)',
	'Milpark Business School',
	'Milpark Education',
	'Mnambithi College',
	'Monash South Africa ',
	'Mopani South East College',
	'Motheo College',
	'Nkangala College',
	'Northern Cape Rural College',
	'Northlink College',
	'Open Learning Group',
	'Orbit College',
	'Oxbridge Academy',
	'Port Elizabeth College',
	'Potchefstroom Academy',
	'Prestige Academy',
	'Qualitas Career Academy',
	'Rosebank College',
	'SAE Institute of South Africa',
	'SANTS Private Higher Education Institution',
	'Sedibeng College',
	'Sekhukhune College',
	'South Cape College',
	'South West College',
	'Southern African Wildlife College',
	'St Augustine Private Tertiary Institution of South Africa',
	'Stenden South Africa',
	'Taletso College',
	'The Da Vinci Institute',
	'The South African College of Applied Psychology (SACAP)',
	'TowerStone Leadership Centre',
	'Tshwane North College',
	'Tshwane South College',
	'Umfolozi College',
	'Umgungundlovu College',
	'Varsity College',
	'Vhembe College',
	'Vuselela College',
	'Waterberg College',
	'West Coast College',
	'Westcol College',
	'Abakholwe Community Developers (PTY) Ltd',
	'Academy at Vaal Triangle',
	'Academy of Business & Computer Studies - Pretoria (Head Office)',
	'Academy of Business & Computer Studies-Durban',
	'Academy of Training and Development',
	'Academy of Training and Development – KWT',
	'Adequate Technical College',
	'African Academy for the Built Environment',
	'Aranda Learnership College',
	'Baal-Perazim FET College (Pty) Ltd',
	'Be Competent Training Institute (PTY) Ltd',
	'Berea Technical College (Pty) Ltd 539',
	'Best Performers College',
	'Bolton Business College and Computer Studies PTY LTD',
	'Central Technical College (Pty) Ltd - Durban',
	'Central Technical College (Pty) Ltd',
	'Central Technical College (Pty) Ltd - Cape Town',
	'Churchil Technical College (Pty) Ltd',
	'Circle Way Training - ARNOT',
	'Cresta Vaal College Potchefstroom',
	'CTU Training Solutions',
	'Dam Technical College',
	'Dam Technical College Pretoria',
	'DCC FET Institution (PTY) LTD',
	'Delcom training institute',
	'Denver Technical College',
	'Divoh Tech (PYT) LTD',
	'Gauteng Central College',
	'Gauteng City College',
	'Greenview training and Development Skills Centre',
	'Growth Path Projects (Pty) Ltd',
	'ICALC Training Academy (Pty) Ltd',
	'Ikage SD College',
	'Immaculate College of Commerce & Engineering',
	'Innovatus FET College',
	'Jeppe College of Commerce and Computer Studies - Johannesburg',
	'Johannesburg City College',
	'Johannesburg Institute of Engineering & Technology',
	'Kalideen Management Services',
	'Life Prep College (Pty) Ltd',
	'Maccosy Business & Computer Training',
	'Madzahisi College',
	'Management and Leadership Academy - Durban City Campus',
	'Management and Leadership Academy - Pietermaritzburg',
	'Mbowa College',
	'NCM Computer and Business Academy',
	'Nkangala training centre',
	'Northern Technical College',
	'Opportunity Learning Centre',
	'Opt Engineering Fet College',
	'Pax Commercial College (PTY) LTD',
	'Polokwane Technology Institute (PTY) LTD.',
	'Pro-Active Public Services College',
	'Richfield Graduate Institute of Technology (Pty) Ltd',
	'Rostec Technical FET College (Pty) Ltd',
	'Springfield FET College PTY LTD',
	'TEKmation Training Institute',
	'Thasullulo FET College',
	'Damelin - Mowbray Campus',
	'Damelin - Cape Town City Campus',
	'Damelin - Management College',
	'Damelin - East London',
];
