version: '3'
services: 
    smartassist:
        build: .
        ports: 
            - "6001:6001"
        volumes:
            - models:/app/models
            - NotebookDataset:/app/NotebookDataset



volumes: 
    models:

    NotebookDataset:
