name: Continous Deployment Develop

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  firebase-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
     
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Setup Angular
        run: npm install -g @angular/cli
    
      - name: Download Dependencies
        run: npm ci
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: smartstudentnotebook
          channelId: live
